title: My Blog
description: My Blog, where I write sometimes.
show_downloads: true

baseurl: "/blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://akshatkarani.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Akshat Karani"
image: /thumbnail-jumbo.png
twitter:
  username: akshatkarani
github:
  username: akshatkarani

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow